### ISSUE TITLE
the storage size result

### ISSUE THREAD

**Issue by PeterFWS** [maincold2/Compact-3DGS#10]
Dear authors,

May I ask how you calculate the storage size of your model, e.g. trained on Mip-360 dataset, where you report avg. 48.82MB in the paper. 

I reproduced the training on Mip-360 dataset from my side, on the opensourced 7 scenes. 
However, I got the storage size (point cloud + checkpoint saved under folder point_cloud/iteration_30000/) way higher than your reported number. 

For example, I have the size for data **stump** 122MB (94MB point cloud data + 49MB the hash-grid and mlp), while your number is 54.66MB in the paper.

Did I miss something? 

Best,

**Comment by PeterFWS** [comment]
ok, now I see your result written in **storage**

**Comment by maincold2** [comment]
Thank you for your interest in our work!

One of the reasons is the usage of the 32FP weight container in Pytorch, despite the weights themselves having a smaller bit-width (e.g., 16FP for positions and I-NGP representations). 
This is a common practice for ease of implementation (e.g., simply saving and loading weights) in Pytorch, and this issue could be easily addressed by selecting the appropriate file format for saving in each specific case.
Similarly, we store already indexed weights with R-VQ, rather than integer indices. (https://github.com/maincold2/Compact-3DGS/issues/9#issuecomment-1898075335)
We assume and calculate the storage for the actually needed bit-width, as reflected in the storage file.
